import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '../../Provider'
import { AuthProvider } from '../../AuthProvider'
import SideNavigationBar from '../../_components/layout/SideNavigationBar'
import { Flex } from '@chakra-ui/react'
import HaikuGenerator from '@/app/_components/widgets/HaikuGenerator'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Flex height="100vh" justifyContent={'space-between'}>
      <SideNavigationBar />
      {children}

      <Flex maxWidth={'400px'}>
        <HaikuGenerator />
      </Flex>
    </Flex>
  )
}
